name: Sync Markdown from Dropbox

on:
  schedule:
    - cron: "0 9 * * *" # 매일 오전 9시 (UTC 기준)
    - cron: "0 11 * * *" # 오전 11시
    - cron: "0 13 * * *" # 오후 1시
  workflow_dispatch: # 수동 실행도 가능하게

jobs:
  sync-md-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.name "김보성"
          git config --global user.email "bocastle1213@gmail.com"

      - name: Download Markdown file from Dropbox
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        run: |
          curl -X POST https://content.dropboxapi.com/2/files/download \
            --header "Authorization: Bearer $DROPBOX_ACCESS_TOKEN" \
            --header "Dropbox-API-Arg: {\"path\": \"/Apps/myapp/auto.md\"}" \
            --output auto.md

      - name: Commit and Push if Changed
        run: |
          mkdir -p contents
          mv auto.md contents/
          git add contents/auto.md
          git commit -m "Auto-sync from Dropbox" || echo "No changes to commit"
          git push origin main
