name: Sync Markdown from Dropbox

on:
  schedule:
    - cron: "0 12 * * *" # UTC 기준으로 오후 9시 (한국시간)
  workflow_dispatch:

jobs:
  sync-md-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.name "김보성"
          git config --global user.email "bocastle1213@gmail.com"

      - name: Calculate today's date
        id: time
        run: |
          echo "DATE=$(date +'%Y_%m_%d')" >> $GITHUB_ENV

      - name: Download Markdown files from Dropbox
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          DATE: ${{ env.DATE }}
        run: |
          DATE=${{ env.DATE }}
          echo "Checking Dropbox for /$DATE"

          # Dropbox API 호출하여 파일 목록 가져오기
          response=$(curl -s -X POST https://api.dropboxapi.com/2/files/list_folder \
            --header "Authorization: Bearer $DROPBOX_ACCESS_TOKEN" \
            --header "Content-Type: application/json" \
            --data "{\"path\": \"/$DATE\"}")

          echo "API Response: $response"

          # 파일 목록이 존재하는지 체크
          FILE_LIST=$(echo "$response" | jq -r '.entries[].name' | tr ' ' '\n')
          if [ -z "$FILE_LIST" ]; then
            echo "No files found or API error."
            exit 0
          else
            echo "Files found: $FILE_LIST"
          fi

          # 파일 목록을 순회하며 처리
          for FILE in $FILE_LIST; do
            echo "Checking file: $FILE"
            if [[ $FILE =~ ^JavaScript_.*\.md$ ]]; then
              echo "Found file: $FILE"
              
              # Dropbox에서 파일 다운로드
              curl -X POST https://content.dropboxapi.com/2/files/download \
                --header "Authorization: Bearer $DROPBOX_ACCESS_TOKEN" \
                --header "Dropbox-API-Arg: {\"path\": \"/$DATE/$FILE\"}" \
                --output temp.md || { echo "File download failed for $FILE"; exit 1; }
              
              # 카테고리와 제목 추출 (파일명으로부터)
              CATEGORY=$(echo $FILE | cut -d'_' -f1)
              TITLE=$(echo $FILE | cut -d'_' -f2- | sed 's/.md//')
              echo "Category: $CATEGORY"
              echo "Title: $TITLE"

              if [ -f temp.md ]; then
                echo "temp.md exists, moving file..."
                mkdir -p $CATEGORY
                mv temp.md $CATEGORY/$TITLE.md
                git add $CATEGORY/$TITLE.md
              else
                echo "temp.md does not exist, skipping move"
              fi
            else
              echo "File did not match: $FILE"
            fi
          done

      - name: Commit and Push if files exist
        run: |
          if git diff --cached --exit-code; then
            echo "No changes to commit"
          else
            git commit -m "Auto-sync: Updated Markdown files"
            git push origin main
          fi
