# 워크플로우 이름 정의
# 이메일 발송
name: Send Mail

# 워크플로우 실행 조건 설정
on:
  workflow_dispatch:

# 작업 정의
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: GitHub Action 결과
          to: target@example.com
          from: "GitHub Action <${{ secrets.SMTP_USER }}>"
          body: 워크플로우가 실패했습니다. 로그를 확인하세요.
